### ISSUE TITLE
I'm trying to retrieve firebase data and read the values ​​one by one

### ISSUE THREAD

**Issue by Pratamatanar** [mobizt/FirebaseJson#23]
Hi, im students from indonesian and I'm a beginner in IOT and want to try to retrieve all the values ​​in Firebase and read them one by one and and I get an error in this part of the code`
FirebaseJson json;
FirebaseJsonData Jsondata
json.get(Jsondata, "/alarm");
    if (Jsondata.success)
    {

         
            FirebaseJson json3;
            Jsondata.getJSON(json3);
            size_t count = json3.iteratorBegin();
            for (size_t i = 0; i < count; i++)
            {
                FirebaseJson::IteratorValue value = json3.valueAt(i);
                Serial.println(value.value.c_str());
                if(String(value.value.c_str()) == time){
                  Serial.println("the time is same");
                  }
            }

            Serial.println();
            json3.iteratorEnd();
    }
else{
Serial.println("Failed to get the alarm");
Serial.println(json.errorPossition);
}
`
but when I try the code on the serial monitor it says like this`
Failed to get the alarm
-1
Failed to get the alarm
-1
Failed to get the alarm
-1
Failed to get the alarm
-1
`
and this is the data that is in firebase `
{ "alarm": {
    "-NQF0Wy4BqMRi-8Twr8y": "14:16",
    "-NQF0i1yEN3g3mqLCUOO": "02:16",
    "-NQF0kbTvQcDEqFQbz6X": "02:16",
    "-NQF0nSiEXBn9weXgnKR": "19:09",
    "-NQG7KoHsv674oETJ2s6": "16:13",
    "-NQP5ONwpNvqrKmXVyE8": "15:13"
  }}`
I'm sorry if you don't understand my words because I used Google Translate to translate the words earlier

**Comment by mobizt** [comment]
Because the key or path to parse JSON data is not valid.

The path should include the UID key like this.
 
`json.get(Jsondata, "/alarm/-NQF0Wy4BqMRi-8Twr8y");`

The UID key will be auto generated by Firebase when you call `Firebase.pushXXX`.


I recommend using query to filter data instead when you don't know the UID key.
https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/DataFilter/DataFilter.ino

The UID key can be obtained from `fbdo.pushName()` after you called `Firebase.pushXXX`
