### ISSUE TITLE
Identity & Future Support

### ISSUE THREAD

**Issue by southerndevz** [mobizt/FirebaseJson#25]
Hi @mobizt,

I see that in the new Firebase Client library you are using JSON Writer. I really liked this JSON parser since it is very flexible. I tried using ArduinoJSON but it isn't so good with JSON Arrays since they are references to JSON documents and it requires a lot of serialize/deserialze functions, it's really a complicated headache. On the other hand this library deserves its place among the JSON serializers / deserializers since its so easy to used. 

* Are there any reasons why you are turning away from it in your examples?
* Will it be deprecated and probably be called by a new name?

I really wish that it can be identifiable by another name since FirebaseJSON makes it look like its for Firebase only but it is so versatile and good. What are your plans and recommendations about it?

**Comment by mobizt** [comment]
For the `FirebaseClient` library, I intend to make it widely supports most Arduino devices.

I use external network client than create internally and Arduino String was used instead of the internal `MB_String` class which is a part of `FirebaseJson`.

I mentioned `MB_String` because it is the class that included in `FirebaseJson` library and used as a core of old `Firebase` library.

The string to number conversion is the reason that I switch to use Arduino String as it is generally available in many platforms.

The string to number conversion in `MB_String` is limited and it may not be compatible with some devices that compile in different C++ compiler version (GCC).

The `MB_String` has more functions similar to C++ string and the old library used mostly functions of it which causes bigger bin file after compile. 

By switching from `MB_String`, the `PSRAM` is only used in temporary buffer.

For the `FirebaseJson`, that used in the old Firebase library for the payload serialization/deserialization.

The internal JSON object and JSON array are created for each `FirebaseData` object. The memory usage is quite large as memory was allocated for many elements in the JSON object when compared to the memory used by String that contains JSON. 

The memory usage is the most important for async client because many requests and responses required more memory.

In ESP8266, its default stack memory is only 4k and half of it used by `BearSSL` client library then memory usage is needed to be optimized.

For the serialization, the object writer class can be used for user JSON input data. We have to use `object_t` object that represent the JSON object as JSON input data.

We don't allow JSON serialized string as input data because we don't know that data is the normal string or JSON serialized string, and we don't want to verify or check user input data.

By excluding `FirebaseJson` from `FirebaseClient` it can reduce the bin size up to 100k.

By removing `FirebaseJson` as a JSON built-in library of `FirebaseClient`, it does not mean that the `FirebaseJson` is deprecated.

It is still active development.  And it is still a part of old Firebase library, I have no plan for renaming it.

FYI.

The `FirebaseJson` may take longer time to search the target node when using set. It is convenient for user, but it is compromised in performance.
