### ISSUE TITLE
memory.h

### ISSUE THREAD

**Issue by smshariatzadeh** [mobizt/FirebaseJson#5]
where I can find memory.h that used in FirebaseJson.h ?

**Comment by mobizt** [comment]
The memory is the C++ standard header which included from file **memory** (no file extension) e.g. for esp8266 it will be at **C:\Users\YourPCName\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\4.8.2**

If you installed the toolchains or board libraries properly or choose the board that supported by the library (ESP8266, ESP32 and Teensy), you will not get this error because of the toolchains and C/C++ compiler are installed properly.

Some Arduino boards may not support due to the compiler for that board is not support the std C++ functions.
